#!/usr/bin/env php
<?php
/**
 * parser
 * Created by: 5-HT.
 * Date: 16.01.2020 16:39
 *
 * ${PARAM_DOC}
 * ${THROWS_DOC}
 */



require __DIR__ . '/vendor/autoload.php';



# TO HELP
$help = new Src\Help\Help;
$help->printHelp();